### ISSUE TITLE
Error - IndexError: List index out of range

### ISSUE THREAD

**Issue by bobberb** [chris-belcher/joinmarket#117]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "tumbler.py", line 188, in run
    self.send_tx(tx, self.balance_by_mixdepth[tx['srcmixdepth']], sweep)
  File "tumbler.py", line 134, in send_tx
    orders, total_cj_fee = choose_order(self.taker.db, amount, tx['makercount'], weighted_order_choose)
  File "//common.py", line 418, in choose_order
    chosen_order = chooseOrdersBy(orders, n, lambda k: k[2])
  File "//common.py", line 362, in weighted_order_choose
    phi = feekey(orders[M]) - minfee
IndexError: list index out of range

**Comment by bobberb** [comment]
New to this, not sure what this error is telling me to fix

**Comment by chris-belcher** [comment]
Could you post more of the log immediately before that crash

If you indent each line it will
    show as code blocks

**Comment by chris-belcher** [comment]
Actually I know what happened. Should be fixed.
