### ISSUE TITLE
socks.py bug, raise Socks5Error

### ISSUE THREAD

**Issue by CohibAA** [chris-belcher/joinmarket#143]
[2015/07/07 11:15:21] Traceback (most recent call last):
      File "/home/redacted/joinmarket/yield-gen-utxofee-REL-fee.py", line 175, in main
        irc.run()
      File "/home/redacted/joinmarket/lib/irc.py", line 461, in run
        self.sock.connect(self.serverport)
      File "/home/redacted/joinmarket/lib/socks.py", line 369, in connect
        self.__negotiatesocks5(destpair[0],destpair[1])
      File "/home/redacted/joinmarket/lib/socks.py", line 236, in __negotiatesocks5
        raise Socks5Error(ord(resp[1]),_generalerrors[ord(resp[1])])
    TypeError: __init__() takes exactly 2 arguments (3 given)

[Line 236, socks.py](https://github.com/chris-belcher/joinmarket/blob/master/lib/socks.py#L236)

[Possible cause, workaround](https://stackoverflow.com/questions/20304301/how-to-control-tor-when-use-tor-proxy)

I don't know enough about this protocol yet to try to fix this one, hopefully someone can debug and fix.

**Comment by abitfan** [comment]
How can we replicate this ?

**Comment by CohibAA** [comment]
It seems to happen when irc is disconnected for unknown reasons and fails to reset/reconnect while running yield-generator.  I haven't seen it happen on a clearnet connection.  Perhaps a problem with the tor hidden service and/or socks connection.  I can't seem to force it to replicate, and the few times I have caught it I couldn't precisely determine what had caused the irc connection to need to reset.
