### ISSUE TITLE
new-yieldgen-algo/yield-generator.py#L101-L102

### ISSUE THREAD

**Issue by CohibAA** [chris-belcher/joinmarket#153]
new-yieldgen-algo crashes while creating absorder under certain conditions and does not start bot, problem may be related to [thecjfee[oid]](https://github.com/chris-belcher/joinmarket/blob/new-yieldgen-algo/yield-generator.py#L101-L102), as shown:

    [2015/07/17 00:15:38] mixdepth_balance_min = [(4, xxxxxxxx, xxxxxxxx), (1, xxxxxxxx, xxxxxxxx), (2, xxxxxxxx, xxxxxxxx), (3, xxxxxxxx, xxxxxxxx), (0, xxxxxxxx, xxxxxxxx)]
    Traceback (most recent call last):
      File "yield-gen-NEW-ALGO.py", line 239, in <module>
        main()
      File "yield-gen-NEW-ALGO.py", line 226, in main
        maker = YieldGenerator(irc, wallet)
      File "yield-gen-NEW-ALGO.py", line 49, in __init__
        Maker.__init__(self, msgchan, wallet)
      File "/home/redacted/joinmarket/lib/maker.py", line 176, in __init__
        self.orderlist = self.create_my_orders()
      File "yield-gen-NEW-ALGO.py", line 101, in create_my_orders
        absorder_fee = calc_cj_fee('relorder', thecjfee[oid], minsize)
    IndexError: list index out of range

**Comment by chris-belcher** [comment]
ack

**Comment by chris-belcher** [comment]
probably fixed here https://github.com/chris-belcher/joinmarket/commit/f38074cdef81880c4183f876b5e335e10aaee344
