### ISSUE TITLE
transaction.py - TypeError: Odd-length string

### ISSUE THREAD

**Issue by CohibAA** [chris-belcher/joinmarket#184]
[2015/08/10 09:41:48] rpc: getrawtransaction ['redactedtransid']
    ----------------------------------------
    Exception happened during processing of request from ('127.0.0.1', 42250)
    Traceback (most recent call last):
      File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
        self.process_request(request, client_address)
      File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
        self.finish_request(request, client_address)
      File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
        self.RequestHandlerClass(request, client_address, self)
      File "/home/cohibaa/joinmarket/lib/blockchaininterface.py", line 326, in __init__
        BaseHTTPServer.BaseHTTPRequestHandler.__init__(self, request, client_address,    base_server)
      File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
        self.handle()
      File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
        self.handle_one_request()
      File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
        method()
      File "/home/cohibaa/joinmarket/lib/blockchaininterface.py", line 340, in do_HEAD
        txd = btc.deserialize(tx)
      File "/home/cohibaa/joinmarket/lib/bitcoin/transaction.py", line 48, in deserialize
        return json_changebase(deserialize(binascii.unhexlify(tx)),
    TypeError: Odd-length string

Any ideas what might be causing this?  It did not crash the yield-gen bot, but kept repeating this error every time rpc getrawtransaction was called, and FWIW bitcoin-cli and curl to jsonrpc returns the raw transaction properly when called manually from the terminal.  This was using master with https://github.com/chris-belcher/joinmarket/pull/141, https://github.com/chris-belcher/joinmarket/pull/172, https://github.com/chris-belcher/joinmarket/pull/173 patches.  

The transaction id was valid, and the transaction was propagated and confirmed.  If it helps, I can provide the actual txid.  Otherwise, if it's not clear to someone smarter than I what caused this, I'll start reverting patches and retest until I can figure out the cause... thanks!

**Comment by AdamISZ** [comment]
Total guess, don't have time to look into it, but maybe the absence of the .strip() in #141 ?

I'd suggest doing the rpc call manually and take a look, but if it's that you won't see it (it's a \n I think)

**Comment by chris-belcher** [comment]
According to google, `TypeError: Odd-length string` appears when a hex string cant be parsed into bytes.
Maybe `tx` is not proper hexadecimal?

**Comment by CohibAA** [comment]
Will reopen if I am actually having an issue.  I think this was a config error.
