### ISSUE TITLE
yield-generator fails if unconfirmed transaction isn't seen

### ISSUE THREAD

**Issue by dooglus** [chris-belcher/joinmarket#213]
commit 850e8194ecc88a60bb4288ec3704678eb5172cc7
Author: chris-belcher <chris-belcher@users.noreply.github.com>
Date:   Mon Aug 31 19:39:36 2015 +0100

My wallet never saw the unconfirmed join transaction before it saw it in a block.

on_tx_unconfirmed() didn't run, but on_tx_confirmed() did.

on_tx_confirmed() tried to access self.tx_unconfirm_timestamp[cjorder.cj_addr] but it hadn't been set, and so an exception occurred:

    [2015/09/01 20:50:19] <<pubmsg nick=Meyofawic message=!absorder 0 10000 223725421 10000 10000 ~
    [2015/09/01 20:54:27] rpc: getrawtransaction ['4f74d2667542988c1e5cf2535d503b185124c1bfdd4c717421e92c7c5dfd9f98']
    [2015/09/01 20:54:27] rpc: gettxout ['4f74d2667542988c1e5cf2535d503b185124c1bfdd4c717421e92c7c5dfd9f98', 0, True]
    [2015/09/01 20:54:27] rpc: listunspent []
    [2015/09/01 20:54:27] bitcoind sync_unspent took 0.0365281105042sec
    [2015/09/01 20:54:27] tx in a block
    [2015/09/01 20:54:27] earned = 0
    ----------------------------------------
    Exception happened during processing of request from ('127.0.0.1', 57880)
    Traceback (most recent call last):
      File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
        self.process_request(request, client_address)
      File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
        self.finish_request(request, client_address)
      File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
        self.RequestHandlerClass(request, client_address, self)
      File "/home/user/Programs/joinmarket/lib/blockchaininterface.py", line 326, in __init__
        BaseHTTPServer.BaseHTTPRequestHandler.__init__(self, request, client_address, base_server)
      File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
        self.handle()
      File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
        self.handle_one_request()
      File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
        method()
      File "/home/user/Programs/joinmarket/lib/blockchaininterface.py", line 366, in do_HEAD
        confirmfun(txd, txid, txdata['confirmations'])
      File "/home/user/Programs/joinmarket/lib/maker.py", line 121, in confirm_callback
        confirmations, txid)
      File "yield-generator.py", line 119, in on_tx_confirmed
        confirm_time = int(time.time()) - self.tx_unconfirm_timestamp[cjorder.cj_addr]
    KeyError: '17c2aHPgXV5LJiF4bJrfiC9dXLFLq6opFY'
    ----------------------------------------
    [2015/09/01 21:07:01] <<pubmsg nick=Qazupijuy message=!absorder 0 10000 223725421 10000 10000 ~

**Comment by chris-belcher** [comment]
Good bug, thanks.

**Comment by CohibAA** [comment]
This seems to happen if the local bitcoin node does not include the transaction in it's mempool.  This can happen for a variety of reasons I think, but the most common is fees are below what the node accepts.  Other (miner) nodes may accept the transaction and include in a block, while the maker's node is "ignoring" the transaction (until it is included in a block).  

In this transaction, the default fee (0.0001) was included, so perhaps the local node has mintxfee= set greater than 0.0001 in bitcoin.conf?

I believe this can also happen when using blockr as the blockchain source, if they do not include the transaction in their mempool for whatever reason(s).

A (possible) solution would be to have the bot run order comparisons and announce changes again when a tx is in a block, instead of only when the unconfirmed transaction is noticed.

**Comment by CohibAA** [comment]
https://github.com/CohibAA/joinmarket-dev-cohibaa/commit/8965b9593a4436fcd2d7ef89a4250be7ece2ae47 will prevent this crash, but see the important notes.  I can clean up the comments and additional debug logging to submit a PR, unless someone plans to fix this issue in a different, more effective manner.
