### ISSUE TITLE
stack trace shows up each time I receive a new transaction

### ISSUE THREAD

**Issue by dooglus** [chris-belcher/joinmarket#219]
I keep seeing this in the standard output of the yield-generator process:

    [2015/09/04 17:35:49] ran confirmfun
    127.0.0.1 - - [04/Sep/2015 17:35:49] "HEAD /walletnotify?e2e97bdaeaef7604e7b8dc74b9960a2547c7e06fe28d726f8ac8d6cf08af16c7 HTTP/1.1" 200 -
    ----------------------------------------
    Exception happened during processing of request from ('127.0.0.1', 46538)
    Traceback (most recent call last):
      File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
        self.process_request(request, client_address)
      File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
        self.finish_request(request, client_address)
      File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
        self.RequestHandlerClass(request, client_address, self)
      File "/home/user/Programs/joinmarket/lib/blockchaininterface.py", line 326, in __init__
        BaseHTTPServer.BaseHTTPRequestHandler.__init__(self, request, client_address, base_server)
      File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
        self.finish()
      File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
        self.wfile.close()
      File "/usr/lib/python2.7/socket.py", line 279, in close
        self.flush()
      File "/usr/lib/python2.7/socket.py", line 303, in flush
        self._sock.sendall(view[write_offset:write_offset+buffer_size])
    error: [Errno 32] Broken pipe
    ----------------------------------------
    [2015/09/04 17:37:45] <<pubmsg nick=Ludaxutaf message=!absorder 0 547 1764159 1000 1500!relorder 1 1764160 1025084819 1000 0.00085 ~

It doesn't seem to cause a problem; joins are being created, detected, and logged just fine, but it's odd that I keep seeing this error.

**Comment by tailsjoin** [comment]
[#194](https://github.com/chris-belcher/joinmarket/issues/194) is this same issue.

**Comment by CohibAA** [comment]
@dooglus Would you please confirm if this occurred when connected via [tor, or clearnet](https://github.com/chris-belcher/joinmarket/issues/194#issuecomment-137921996)?

**Comment by dooglus** [comment]
Clearnet.

**Comment by dooglus** [comment]
Closing as dup.
