### ISSUE TITLE
JSON-RPC connection failed

### ISSUE THREAD

**Issue by JulianTosh** [chris-belcher/joinmarket#227]
I'm running bitcoind and joinmarket on their own systems and using rpc to connect the two.

When I run wallet-tool.py as specified to test the connection, I get "JSON-RPC connection failed".

I've disabled all firewalls, tested ports, and verified the rpc password. Here is the output of my debugging adventures:
```
<------------ BITCOIND HOST 192.168.0.12 --------------------->
 
[blockchain@blockchain ~]$ systemctl status firewalld
firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled)
   Active: inactive (dead)
 
[blockchain@blockchain ~]$ netstat --listening --tcp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 blockchain.*******:8332 0.0.0.0:*               LISTEN    
tcp        0      0 localhost:8332          0.0.0.0:*               LISTEN    
tcp        0      0 0.0.0.0:ssh             0.0.0.0:*               LISTEN    
tcp        0      0 localhost:smtp          0.0.0.0:*               LISTEN    
tcp        0      0 0.0.0.0:60795           0.0.0.0:*               LISTEN    
tcp6       0      0 localhost:8332          [::]:*                  LISTEN    
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN    
tcp6       0      0 [::]:47672              [::]:*                  LISTEN    
tcp6       0      0 localhost:smtp          [::]:*                  LISTEN    
[blockchain@blockchain ~]$ cat .bitcoin/bitcoin.conf
rpcuser=bitcoinrpc
rpcpassword=***********
server=1
daemon=1
bind=192.168.0.12
port=8332
#whitebind=192.168.0.12:8332
whitelist=255.255.255.0
 
#JoinMarket
walletnotify=curl -sI --connect-timeout 1 http://192.168.0.13:62602/walletnotify?%s
alertnotify=curl -sI --connect-timeout 1 http://192.168.0.13:62602/alertnotify?%s
[blockchain@blockchain ~]$ bitcoin-cli getblockcount
192610
[blockchain@blockchain ~]$ ip addr show eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    inet 192.168.0.12/24 brd 192.168.0.255 scope global eth0
 
 
 
<------------ JOINMARKET HOST 192.168.0.13 --------------------->
[root@joinmarket ~]# nmap -sS 192.168.0.12 -p 8332
 
Starting Nmap 6.40 ( http://nmap.org ) at 2015-09-10 06:49 PDT
Nmap scan report for blockchain.moraine.tosh.us (192.168.0.12)
Host is up (0.00023s latency).
PORT     STATE SERVICE
8332/tcp open  unknown
 
Nmap done: 1 IP address (1 host up) scanned in 0.14 seconds
[root@joinmarket ~]# su - joinmarket
Last login: Thu Sep 10 06:41:16 PDT 2015 on pts/0
[joinmarket@joinmarket joinmarket]$ systemctl status firewalld
firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled)
   Active: inactive (dead)
 
[joinmarket@joinmarket joinmarket]$ cat joinmarket.cfg
[BLOCKCHAIN]
blockchain_source = bitcoin-rpc
#blockchain_source = blockr
#options: blockr, json-rpc, regtest
#before using json-rpc read https://github.com/chris-belcher/joinmarket/wiki/Running-JoinMarket-with-Bitcoin-Core-full-node
network = mainnet
bitcoin_cli_cmd = bitcoin-cli
rpc_host = 192.168.0.12
rpc_port = 8332
rpc_user = bitcoinrpc
rpc_password = *************
 
[MESSAGING]
host = irc.cyberguerrilla.org
channel = joinmarket-pit
port = 6697
usessl = true
socks5 = false
socks5_host = localhost
socks5_port = 9150
#for tor
#host = 6dvj6v5imhny3anf.onion
#port = 6667
#usessl = false
#socks5 = true
[joinmarket@joinmarket joinmarket]$ curl http://192.168.0.12:8332
curl: (52) Empty reply from server
[joinmarket@joinmarket joinmarket]$ python wallet-tool.py wallet.json
Traceback (most recent call last):
  File "wallet-tool.py", line 45, in <module>
    load_program_config()
  File "/home/joinmarket/workspace/joinmarket/lib/common.py", line 79, in load_program_config
    bc_interface = blockchaininterface.get_blockchain_interface_instance(config)
  File "/home/joinmarket/workspace/joinmarket/lib/blockchaininterface.py", line 56, in get_blockchain_interface_instance
    bc_interface = BitcoinCoreInterface(rpc, network)
  File "/home/joinmarket/workspace/joinmarket/lib/blockchaininterface.py", line 413, in __init__
    blockchainInfo = self.jsonRpc.call("getblockchaininfo", [])
  File "/home/joinmarket/workspace/joinmarket/lib/jsonrpc.py", line 106, in call
    response = self.queryHTTP (request)
  File "/home/joinmarket/workspace/joinmarket/lib/jsonrpc.py", line 95, in queryHTTP
    raise JsonRpcConnectionError ("JSON-RPC connection failed")
jsonrpc.JsonRpcConnectionError: JSON-RPC connection failed
```

**Comment by JulianTosh** [comment]
In bitcoin.conf, I removed the whitelist line and replaced it with rpcallow.

```
rpcallowip=192.168.0.0/24
```

Still no luck. I did load up tcpdump on the bitcoin host and was able to confirm a tcp connection from the joinmarket host on port 8332.

**Comment by chris-belcher** [comment]
No idea.

Update your repo up to https://github.com/chris-belcher/joinmarket/commit/b0aa602b9e8f80a5219bf002e17a9bd2f5c8395b and try again. At least you'll get a meaningful error message this time.

**Comment by JulianTosh** [comment]
Now I get...
```
[joinmarket@joinmarket joinmarket]$ python wallet-tool.py wallet.json
Traceback (most recent call last):
  File "wallet-tool.py", line 45, in <module>
    load_program_config()
  File "/home/joinmarket/workspace/joinmarket/lib/common.py", line 79, in load_program_config
    bc_interface = blockchaininterface.get_blockchain_interface_instance(config)
  File "/home/joinmarket/workspace/joinmarket/lib/blockchaininterface.py", line 56, in get_blockchain_interface_instance
    bc_interface = BitcoinCoreInterface(rpc, network)
  File "/home/joinmarket/workspace/joinmarket/lib/blockchaininterface.py", line 413, in __init__
    blockchainInfo = self.jsonRpc.call("getblockchaininfo", [])
  File "/home/joinmarket/workspace/joinmarket/lib/jsonrpc.py", line 106, in call
    response = self.queryHTTP (request)
  File "/home/joinmarket/workspace/joinmarket/lib/jsonrpc.py", line 95, in queryHTTP
    raise JsonRpcConnectionError ("JSON-RPC connection failed. Err:" + repr(exc))
jsonrpc.JsonRpcConnectionError: JSON-RPC connection failed. Err:BadStatusLine("''",)
```

**Comment by JulianTosh** [comment]
Also, my bitcoind is still pulling blocks around 251013 and counting. Just mentioning that in case bitcoind responds awkwardly if it is not fully sync'd.

**Comment by JulianTosh** [comment]
Well, this sucks... a test to localhost:8332 works, but a test to a routeable socket fails...

```
[blockchain@blockchain ~]$ curl --user bitcoinrpc --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getinfo", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/
{"result":{"version":110000,"protocolversion":70002,"walletversion":60000,"balance":0.00000000,"blocks":254929,"timeoffset":-1,"connections":8,"proxy":"","difficulty":65750060.14908481,"testnet":false,"keypoololdest":1441852887,"keypoolsize":101,"paytxfee":0.00000000,"relayfee":0.00001000,"errors":""},"error":null,"id":"curltest"}
[blockchain@blockchain ~]$ 
[blockchain@blockchain ~]$ 
[blockchain@blockchain ~]$ 
[blockchain@blockchain ~]$ curl --user bitcoinrpc --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getinfo", "params": [] }' -H 'content-type: text/plain;' http://192.168.0.12:8332/
curl: (52) Empty reply from server
```

**Comment by JulianTosh** [comment]
Sorry for wasting everyone's time, but at least my error is documented for the whole world to make fun of me for all eternity.

```
rpcallow=192.168.0.0/24
rpcallow=127.0.0.1
```

should be

```
rpcallowip=192.168.0.0/24
rpcallowip=127.0.0.1
```
