### ISSUE TITLE
wallet-tool.py errors with "No such file or directory"

### ISSUE THREAD

**Issue by JulianTosh** [chris-belcher/joinmarket#230]
Latest pull.

When I run "python wallet-tool.py generate", I get "OSError: [Errno 2] No such file or directory"

```
2015-09-14:0859 PDT
[joinmarket@joinmarket joinmarket]$ pwd
/home/joinmarket/workspace/joinmarket

2015-09-14:0859 PDT
[joinmarket@joinmarket joinmarket]$ git pull
Already up-to-date.

2015-09-14:0859 PDT
[joinmarket@joinmarket joinmarket]$ python wallet-tool.py generate
Traceback (most recent call last):
  File "wallet-tool.py", line 45, in <module>
    load_program_config()
  File "/home/joinmarket/workspace/joinmarket/lib/common.py", line 79, in load_program_config
    bc_interface = blockchaininterface.get_blockchain_interface_instance(config)
  File "/home/joinmarket/workspace/joinmarket/lib/blockchaininterface.py", line 60, in get_blockchain_interface_instance
    bc_interface = BitcoinCoreInterface(rpc, network)
  File "/home/joinmarket/workspace/joinmarket/lib/blockchaininterface.py", line 413, in __init__
    blockchainInfo = self.jsonRpc.call("getblockchaininfo", [])
  File "/home/joinmarket/workspace/joinmarket/lib/blockchaininterface.py", line 36, in call
    res = subprocess.check_output(fullCall)
  File "/usr/lib64/python2.7/subprocess.py", line 568, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by chris-belcher** [comment]
Something is wrong with your configuration. You're using `json-rpc` and maybe don't have `bitcoin_cli_cmd` correctly set?

The recommended way now is to use `bitcoin-rpc`. See the [wiki page](https://github.com/chris-belcher/joinmarket/wiki/Running-JoinMarket-with-Bitcoin-Core-full-node) for instructions.

**Comment by JulianTosh** [comment]
My apologies. I have two installs going at two different locations. I thought this site was further along. I had not fully configured the joinmarket.cfg file and had not correctly set it ti bitcoin-rpc.

This kills the issue.
