### ISSUE TITLE
"killing taker, TODO handle this error" from "outputs unconfirmed or already spent"

### ISSUE THREAD

**Issue by JulianTosh** [chris-belcher/joinmarket#235]
While running tumbler.py...

```
[2015/09/16 04:53:13] rpc: gettxout ['23e95ff2ae0c4080bfa98f692768bda7cbadb6169354c2d5fe6d1fc20c5b09f8', 13, False]
[2015/09/16 04:53:13] ERROR outputs unconfirmed or already spent. utxo_data=[None]


[2015/09/16 04:53:13] Traceback (most recent call last):
  File "tumbler.py", line 332, in main
    irc.run()
  File "/home/joinmarket/workspace/joinmarket/lib/irc.py", line 492, in run
    self.__handle_line(line)
  File "/home/joinmarket/workspace/joinmarket/lib/irc.py", line 395, in __handle_line
    self.__handle_privmsg(chunks[0], chunks[2], get_irc_text(line))
  File "/home/joinmarket/workspace/joinmarket/lib/irc.py", line 348, in __handle_privmsg
    self.__on_privmsg(nick, parsed) 
  File "/home/joinmarket/workspace/joinmarket/lib/irc.py", line 228, in __on_privmsg
    self.on_ioauth(nick, utxo_list, cj_pub, change_addr, btc_sig)
  File "/home/joinmarket/workspace/joinmarket/lib/taker.py", line 287, in on_ioauth
    self.cjtx.recv_txio(nick, utxo_list, cj_pub, change_addr)
  File "/home/joinmarket/workspace/joinmarket/lib/taker.py", line 74, in recv_txio
    raise RuntimeError('killing taker, TODO handle this error')
RuntimeError: killing taker, TODO handle this error
```

More log data here:

http://pastebin.com/qwXUZYyX

**Comment by chris-belcher** [comment]
This crash was caused by the market maker sending a UTXO that had already been spent. Normally the maker bot checks the UTXO is valid before sending, but code must've been modified. I wonder if the operator edited out the lines thinking it will make him more money. Protip: it wont.

By the way, if you're trying out tumbler.py you should try the open pull request where some large improvements are currently being tested. https://github.com/chris-belcher/joinmarket/pull/225
