### ISSUE TITLE
yield-generator crash if blockr returns vout without is_spent

### ISSUE THREAD

**Issue by ande2101** [chris-belcher/joinmarket#263]
[2015/10/08 06:00:21] Traceback (most recent call last):
      File "yield-generator.py", line 147, in main
        irc.run()
      File "/home/user/joinmarket/lib/irc.py", line 502, in run
        self.__handle_line(line)
      File "/home/user/joinmarket/lib/irc.py", line 405, in __handle_line
        self.__handle_privmsg(chunks[0], chunks[2], get_irc_text(line))
      File "/home/user/joinmarket/lib/irc.py", line 358, in __handle_privmsg
        self.__on_privmsg(nick, parsed)
      File "/home/user/joinmarket/lib/irc.py", line 262, in __on_privmsg
        self.on_seen_tx(nick, txhex)
      File "/home/user/joinmarket/lib/maker.py", line 213, in on_seen_tx
        self.active_orders[nick].recv_tx(nick, txhex)
      File "/home/user/joinmarket/lib/maker.py", line 81, in recv_tx
        goodtx, errmsg = self.verify_unsigned_tx(self.tx)
      File "/home/user/joinmarket/lib/maker.py", line 128, in verify_unsigned_tx
        input_utxo_data = common.bc_interface.query_utxo_set(list(tx_utxo_set))
      File "/home/user/joinmarket/lib/blockchaininterface.py", line 314, in query_utxo_set
        if vout['is_spent'] == 1:
    KeyError: 'is_spent'

**Comment by ande2101** [comment]
Update: This could have been because I was using it over Tor and it was using HTTP rather than HTTPS. I've put additional logging in and will see if it goes away.

**Comment by tailsjoin** [comment]
FWIW I've used blockr with Tor extensively over the past months and have never seen this issue.

**Comment by ande2101** [comment]
Interesting. I haven't restarted in ages, perhaps I've just got a bad exit node?

I had a similar issue yesterday before I put the HTTPS changes in:

    Traceback (most recent call last):
      File "yield-generator.py", line 147, in main
        irc.run()
      File "/home/anonymous/Documents/cash/joinmarket/lib/irc.py", line 502, in run
        self.__handle_line(line)
      File "/home/anonymous/Documents/cash/joinmarket/lib/irc.py", line 405, in __handle_line
        self.__handle_privmsg(chunks[0], chunks[2], get_irc_text(line))
      File "/home/anonymous/Documents/cash/joinmarket/lib/irc.py", line 358, in __handle_privmsg
        self.__on_privmsg(nick, parsed)
      File "/home/anonymous/Documents/cash/joinmarket/lib/irc.py", line 262, in __on_privmsg
        self.on_seen_tx(nick, txhex)
      File "/home/anonymous/Documents/cash/joinmarket/lib/maker.py", line 213, in on_seen_tx
        self.active_orders[nick].recv_tx(nick, txhex)
      File "/home/anonymous/Documents/cash/joinmarket/lib/maker.py", line 81, in recv_tx
        goodtx, errmsg = self.verify_unsigned_tx(self.tx)
      File "/home/anonymous/Documents/cash/joinmarket/lib/maker.py", line 128, in verify_unsigned_tx
        input_utxo_data = common.bc_interface.query_utxo_set(list(tx_utxo_set))
      File "/home/anonymous/Documents/cash/joinmarket/lib/blockchaininterface.py", line 312, in query_utxo_set
        txdata = [d for d in data if d['tx'] == txo[:64]][0]
    IndexError: list index out of range

**Comment by tailsjoin** [comment]
After thinking further about this, I haven't really run a yieldgen over Tor/blockr except for a few tests. So I don't think my experience is helpful for this situation as I probably never even came in contact with these scenarios. Sorry to derail your thought process.

**Comment by ande2101** [comment]
Ah okay, no problem. Looks likeI've got intermittent DNS issues too. I think I should make a tor-robustness branch and fix each problem as it I encounter it. The deeper issue is that intermittent network problems shouldn't cause a server to crash, specially if the service is designed to run over a flaky network.

Needs a bit more thought I guess.
