### ISSUE TITLE
"list index out of range" error when running wallet-tool.py with maxmixdepth > 5

### ISSUE THREAD

**Issue by MMMonsterrr** [chris-belcher/joinmarket#268]
Started wallet-tool.py with `-m 7`. It tells me to restart bitcoind with -rescan, which I did. Running it afterwards gives me this error message:

```
Traceback (most recent call last):
  File "wallet-tool.py", line 61, in <module>
    common.bc_interface.sync_wallet(wallet)
  File "/home/someone/joinmarket/lib/blockchaininterface.py", line 80, in sync_wallet
    self.sync_addresses(wallet)
  File "/home/someone/joinmarket/lib/blockchaininterface.py", line 477, in sync_addresses
    wallet.index[mix_depth][forchange] >= wallet.index_cache[mix_depth][forchange]:
IndexError: list index out of range
```

**Comment by OverlordQ** [comment]
FWIW:

```
(Pdb) wallet.index
[[17, 11], [11, 11], [9, 2], [2, 0], [0, 0], [20, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]
(Pdb) wallet.index_cache
[[11, 11], [10, 11], [9, 8], [8, 0], [0, 0]]
(Pdb) mix_depth
5
(Pdb) forchange
0
(Pdb)
```

**Comment by chris-belcher** [comment]
https://github.com/chris-belcher/joinmarket/commit/27b7d72aec56eadff9a1e26ffe7a672a5c3caa11 Hopefully fixed.

**Comment by MMMonsterrr** [comment]
Can confirm that this works now, both with wallet-tool.py as well as yield-generator.py.
