### ISSUE TITLE
Tumbler Option Conflict Error

### ISSUE THREAD

**Issue by tailsjoin** [chris-belcher/joinmarket#270]
Just did a pull and got this:

    $ python tumbler.py --help
    Traceback (most recent call last):
      File "tumbler.py", line 394, in <module>
        main()
      File "tumbler.py", line 274, in main
        default=(0.01, 10000), help=maximum coinjoin fee and bitcoin value the tumbler is 
      File "/usr/lib/python2.7/optparse.py", line 1021, in add_option
        self._check_conflict(option)
      File "/usr/lib/python2.7/optparse.py", line 996, in _check_conflict
        option)
    optparse.OptionConflictError: option -x/--maxcjfee: conflicting option string(s): -x, --maxcjfee

**Comment by chris-belcher** [comment]
Whoops sorry. Should be fine now.

**Comment by tailsjoin** [comment]
Fixed.
