### ISSUE TITLE
bci.py:   Exception: {"status":"fail","data":null,"code":404,"message":"No records found"}

### ISSUE THREAD

**Issue by lacksfish** [chris-belcher/joinmarket#280]
```
...
...
[2015/10/18 16:45:04] key=finishcallback
[2015/10/18 16:45:04] <bound method TumblerThread.finishcallback of <TumblerThread(Thread-2, started daemon 140465357973248)>>
[2015/10/18 16:45:04] key=choose_orders_recover
[2015/10/18 16:45:04] <bound method TumblerThread.tumbler_choose_orders of <TumblerThread(Thread-2, started daemon 140465357973248)>>
[2015/10/18 16:45:04] Traceback (most recent call last):
  File "tumbler.py", line 379, in main
    irc.run()
  File "/storage/Coinstuff/joinmarket/lib/irc.py", line 502, in run
    self.__handle_line(line)
  File "/storage/Coinstuff/joinmarket/lib/irc.py", line 405, in __handle_line
    self.__handle_privmsg(chunks[0], chunks[2], get_irc_text(line))
  File "/storage/Coinstuff/joinmarket/lib/irc.py", line 358, in __handle_privmsg
    self.__on_privmsg(nick, parsed)
  File "/storage/Coinstuff/joinmarket/lib/irc.py", line 231, in __on_privmsg
    self.on_ioauth(nick, utxo_list, cj_pub, change_addr, btc_sig)
  File "/storage/Coinstuff/joinmarket/lib/taker.py", line 414, in on_ioauth
    self.cjtx.recv_txio(nick, utxo_list, cj_pub, change_addr)
  File "/storage/Coinstuff/joinmarket/lib/taker.py", line 86, in recv_txio
    utxo_data = common.bc_interface.query_utxo_set(self.utxos[nick])
  File "/storage/Coinstuff/joinmarket/lib/blockchaininterface.py", line 306, in query_utxo_set
    blockr_data = json.loads(btc.make_request(blockr_url + ','.join(ids)))['data']
  File "/storage/Coinstuff/joinmarket/lib/bitcoin/bci.py", line 23, in make_request
    raise Exception(p)

Exception: {"status":"fail","data":null,"code":404,"message":"No records found"}

done
```
Had some nonrespondants, could this cause the issue?

This is the command I executed:

 $ python tumbler.py -f 20000 -m 0 wallet.json [BTC Adress]

**Comment by chris-belcher** [comment]
Looks like blockr.io didnt respond.

Since you're running tumbler in an effort to get back privacy, you should look into setting up a bitcoin node which is a much more private method of getting blockchain information than querying blockr.io (which by the way is owned by coinbase.com)
