### ISSUE TITLE
crash in sendpayment.py::114

### ISSUE THREAD

**Issue by Giszmo** [chris-belcher/joinmarket#305]
This happens when I try to sendpayment

    chosen orders to fill {u'Romuyojov': 0, u'Cilewiliv': 0} totalcjfee=4
    [2015/11/05 01:33:37] additional coinjoin fee = 0.00121%
    send with these orders? (y/n):Exception in thread Thread-2:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
        self.run()
      File "sendpayment.py", line 114, in run
        self.create_tx()
      File "sendpayment.py", line 65, in create_tx
        self.taker.makercount)
      File "sendpayment.py", line 105, in sendpayment_choose_orders
        if raw_input('send with these orders? (y/n):')[0] != 'y':

**Comment by tailsjoin** [comment]
>if raw_input('send with these orders? (y/n):')[0] != 'y':

Did you put `0` instead of `y` when it asked you to agree with the orders?

**Comment by Giszmo** [comment]
No. That's how it looks before I get to hit any button.

**Comment by Giszmo** [comment]
I guess it only is a bit mixed up because of … threads.

**Comment by tailsjoin** [comment]
Maybe you should explain exactly what you've got going on.  

* What OS are you on?

* Are you using bitcoin core or blockr?

* What command are you issuing (redact btc addresses)?

* Maybe redact sensitive parts and post a longer log.

**Comment by Giszmo** [comment]
* Debian
* blockr
* `python sendpayment.py wallet.json 398348 1Q99VCVR6UkzaiBMJLpVR4xRqR13X8kMkF`

parts are semi-sensitive but last time I ran into this, was yesterday. Maybe has to do with #306 even.

Tag it "works for me" if you want. I'll re-open it with more info if I'm the only one getting this. Thanks for looking into it so far.

**Comment by tailsjoin** [comment]
I'll wait for someone with more knowledge of what could throw those errors. From my experience it seems I can't explain it.
