### ISSUE TITLE
installation on debian fails with AttributeError: 'FFI' object has no attribute 'set_source'

### ISSUE THREAD

**Issue by Giszmo** [chris-belcher/joinmarket#321]
running `$ ./install.sh` terminates with these lines:

     /bin/mkdir -p '/home/leo/workspace/joinmarket/deps/build/secp256k1/include'
     /usr/bin/install -c -m 644 include/secp256k1.h include/secp256k1_ecdh.h include/secp256k1_schnorr.h include/secp256k1_recovery.h '/home/leo/workspace/joinmarket/deps/build/secp256k1/include'
     /bin/mkdir -p '/home/leo/workspace/joinmarket/deps/build/secp256k1/lib/pkgconfig'
     /usr/bin/install -c -m 644 libsecp256k1.pc '/home/leo/workspace/joinmarket/deps/build/secp256k1/lib/pkgconfig'
    make[1]: Leaving directory '/home/leo/workspace/joinmarket/deps/secp256k1'
    Traceback (most recent call last):
      File "build.py", line 316, in <module>
        _ffi = build_ffi(**kwargs)
      File "build.py", line 295, in build_ffi
        ffi.set_source(
    AttributeError: 'FFI' object has no attribute 'set_source'
    $

and I think it does install something ffi-ish 1.3 but I get a lower version like this:

    joinmarket $ python
    Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
    [GCC 4.9.2] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import cffi
    >>> cffi.__version__
    '0.8.6'

(I poked around but don't see how to make it work :( )

**Comment by AdamISZ** [comment]
I'm taking a look at this now but @fivepiece will likely figure it out quicker. For completeness can you give us the exact version of Debian?

**Comment by Giszmo** [comment]
$ uname -a
    Linux locurro 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux

**Comment by Giszmo** [comment]
[install.txt](https://github.com/chris-belcher/joinmarket/files/36705/install.txt)

**Comment by fivepiece** [comment]
@Giszmo , can you try setting all exports as listed in `INSTALL_UBUNTU.md` and then try `cffi.__version__` in python shell again?
Also, check see if you have a package `cffi` installed by either apt or pip:

`apt-cache policy python-cffi`
`pip list | grep cffi`

Thanks!

**Comment by Giszmo** [comment]
leo@locurro:~/workspace/joinmarket$ echo "export joinmarket_home=$(pwd)" >> ~/.bashrc
    leo@locurro:~/workspace/joinmarket$ source ~/.bashrc # after doing the other edits
    leo@locurro:~/workspace/joinmarket$ python
    Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
    [GCC 4.9.2] on linux2
    >>> cffi.__version__
    '0.8.6'
    leo@locurro:~/workspace/joinmarket$ apt-cache policy python-cffi
    python-cffi:
      Installed: 0.8.6-1
      Candidate: 0.8.6-1
      Version table:
     *** 0.8.6-1 0
            500 http://ftp.cl.debian.org/debian/ stable/main amd64 Packages
            100 /var/lib/dpkg/status
    leo@locurro:~/workspace/joinmarket$ pip list | grep cffi
    cffi (0.8.6)
    leo@locurro:~/workspace/joinmarket$

**Comment by Giszmo** [comment]
`$ sudo aptitude remove python-cffi` does resolve the issue but I don't know what other tool I broke doing so.

    >>> cffi.__version__
    '1.3.0'

**Comment by fivepiece** [comment]
Yea, I was trying to avoid asking you to remove it.  I guess python first loads whatever is in `sys.modules`, and only then does it look at `PYTHONPATH`, then even if there's a different version of the same module, only the first version that python knows about is imported (here, the old version).

Tools that might break:
- Anything that specifically needs cffi version 0.8.6
- Anything that specifically looks for python-cffi
- Anything requires cffi and python is not loaded with the `PYTHONPATH` environment variable that points to cffi 1.3.0

I wonder if there's a graceful way to tell python to load a newer version module if it exists..

**Comment by AdamISZ** [comment]
But, I also had 0.8.6 (and still do) on my debian box, but the script runs correctly.
Looking at my install there's a divergence starting on these lines: 

/bin/mkdir -p '/home/adam/joinmarket/deps/build/libffi/share/info'
 /usr/bin/install -c -m 644 ../doc/libffi.info '/home/adam/joinmarket/deps/build/libffi/share/info'
 install-info --info-dir='/home/adam/joinmarket/deps/build/libffi/share/info' '/home/adam/joinmarket/deps/build/libffi/share/info/libffi.info'
***This is not dpkg install-info anymore, but GNU install-info***
See the man page for ginstall-info for command line arguments
 /bin/mkdir -p '/home/adam/joinmarket/deps/build/libffi/lib/pkgconfig'
 /usr/bin/install -c -m 644 libffi.pc '/home/adam/joinmarket/deps/build/libffi/lib/pkgconfig'
make[3]: Leaving directory `/home/adam/joinmarket/deps/libffi/x86_64-unknown-linux-gnu'
make[2]: Leaving directory `/home/adam/joinmarket/deps/libffi/x86_64-unknown-linux-gnu'
make[1]: Leaving directory `/home/adam/joinmarket/deps/libffi/x86_64-unknown-linux-gnu'
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/ptyprocess
copying ptyprocess/util.py -> build/lib.linux-x86_64-2.7/ptyprocess
copying ptyprocess/__init__.py -> build/lib.linux-x86_64-2.7/ptyprocess
copying ptyprocess/ptyprocess.py -> build/lib.linux-x86_64-2.7/ptyprocess
copying ptyprocess/_fork_pty.py -> build/lib.linux-x86_64-2.7/ptyprocess

whereas for @Giszmo it goes:

/bin/mkdir -p '/home/leo/workspace/joinmarket/deps/build/libffi/share/info'
 /usr/bin/install -c -m 644 ../doc/libffi.info '/home/leo/workspace/joinmarket/deps/build/libffi/share/info'
 install-info --info-dir='/home/leo/workspace/joinmarket/deps/build/libffi/share/info' '/home/leo/workspace/joinmarket/deps/build/libffi/share/info/libffi.info'
 /bin/mkdir -p '/home/leo/workspace/joinmarket/deps/build/libffi/lib/pkgconfig'
 /usr/bin/install -c -m 644 libffi.pc '/home/leo/workspace/joinmarket/deps/build/libffi/lib/pkgconfig'
make[3]: Leaving directory '/home/leo/workspace/joinmarket/deps/libffi/x86_64-unknown-linux-gnu'
make[2]: Leaving directory '/home/leo/workspace/joinmarket/deps/libffi/x86_64-unknown-linux-gnu'
make[1]: Leaving directory '/home/leo/workspace/joinmarket/deps/libffi/x86_64-unknown-linux-gnu'
running build
running build_py
running install
running build
running build_py
running install_lib
running install_egg_info
Removing /home/leo/workspace/joinmarket/deps/build/ptyprocess/lib/python2.7/site-packages/ptyprocess-0.5-py2.7.egg-info
Writing /home/leo/workspace/joinmarket/deps/build/ptyprocess/lib/python2.7/site-packages/ptyprocess-0.5-py2.7.egg-info
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running build
running build_py
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install


... and there are more deviations after that in that section.

**Comment by Giszmo** [comment]
I'm pretty sure `virtualenv` was made to deal with version issues. On my last python job that was one of the magics I used without digging deep into. Let me know if I can help with this.

**Comment by AdamISZ** [comment]
I suspect so, yes. If you can help it'd be much appreciated, of course :)
