### ISSUE TITLE
crash running yield generator

### ISSUE THREAD

**Issue by riclas** [chris-belcher/joinmarket#330]
I just got a crash running the yield generator. the traceback is:
[2015/11/23 01:06:59] Traceback (most recent call last):
  File "C:\joinmarket\yield-generator.py", line 150, in main
    irc.run()
  File "C:\joinmarket\lib\irc.py", line 502, in run
    self.__handle_line(line)
  File "C:\joinmarket\lib\irc.py", line 405, in __handle_line
    self.__handle_privmsg(chunks[0], chunks[2], get_irc_text(line))
  File "C:\joinmarket\lib\irc.py", line 358, in __handle_privmsg
    self.__on_privmsg(nick, parsed)
  File "C:\joinmarket\lib\irc.py", line 262, in __on_privmsg
    self.on_seen_tx(nick, txhex)
  File "C:\joinmarket\lib\maker.py", line 213, in on_seen_tx
    self.active_orders[nick].recv_tx(nick, txhex)
  File "C:\joinmarket\lib\maker.py", line 81, in recv_tx
    goodtx, errmsg = self.verify_unsigned_tx(self.tx)
  File "C:\joinmarket\lib\maker.py", line 128, in verify_unsigned_tx
    input_utxo_data = common.bc_interface.query_utxo_set(list(tx_utxo_set))
  File "C:\joinmarket\lib\blockchaininterface.py", line 318, in query_utxo_set
    if vout['is_spent'] == 1:
KeyError: 'is_spent'

belcher suggested on irc that it probably just needs an if(is_spent) on vout

**Comment by AdamISZ** [comment]
This and #344 are curiously similar, in that both seem to refer to errors in json format coming from blockr.io for a yield generator, and both are from @riclas , and others aren't reporting this. I wonder what's going on.

**Comment by riclas** [comment]
i haven't noticed these crashes again fwiw... maybe something temporary on blockr.io side at the time?
