### ISSUE TITLE
patientsendpayment crashes after timeout

### ISSUE THREAD

**Issue by dkaparis** [chris-belcher/joinmarket#331]
OS: Debian
Joinmarket rev: 5e657f834753cefc6ad21dbd764167e20c162545
Using blockr.io for blockchain history and haven't modified any stock settings.
I tried to use patientsendpayment.py several times to sweep my wallet (send amount 0), with the same result: after the time limit expired, it crashed with the following exception:

Exception in thread Thread-2:
Traceback (most recent call last):   
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "patientsendpayment.py", line 45, in run
    self.tmaker.txfee, self.finishcallback)
  File "[...]/joinmarket/lib/taker.py", line 400, in start_cj
    choose_orders_recover, auth_addr)
  File "[...]/joinmarket/lib/taker.py", line 25, in __init__
    self.active_orders = dict(orders)
TypeError: 'NoneType' object is not iterable

After the failure I was able to sweep the wallet with sendpayment.py without issue.

**Comment by chris-belcher** [comment]
Unfortunately patientsendpayment cant work at all right now because of #88 JoinMarket needs a protocol update.
