### ISSUE TITLE
yield-generator crashes with 'wrongly using an already spent utxo'

### ISSUE THREAD

**Issue by domob1812** [chris-belcher/joinmarket#69]
My `yield-generator.py` process crashed with this error:

...
[2015/05/12 02:50:12] key=serverport
[2015/05/12 02:50:12] ('irc.snoonet.org', 6697)
[2015/05/12 02:50:12] key=userrealname
[2015/05/12 02:50:12] ('username', 'btcint=json-rpc')
[2015/05/12 02:50:12] key=fd
[2015/05/12 02:50:12] <socket._fileobject object at 0x7f584062b2d0>
[2015/05/12 02:50:12] key=on_order_cancel
[2015/05/12 02:50:12] None
[2015/05/12 02:50:12] Traceback (most recent call last):
  File "yield-generator.py", line 131, in main
    irc.run()
  File "/usr/src/joinmarket/lib/irc.py", line 472, in run
    self.__handle_line(line)
  File "/usr/src/joinmarket/lib/irc.py", line 374, in __handle_line
    self.__handle_privmsg(chunks[0], chunks[2], get_irc_text(line))
  File "/usr/src/joinmarket/lib/irc.py", line 338, in __handle_privmsg
    self.__on_privmsg(nick, parsed)
  File "/usr/src/joinmarket/lib/irc.py", line 233, in __on_privmsg
    self.on_order_fill(nick, oid, amount, taker_pk)
  File "/usr/src/joinmarket/lib/maker.py", line 192, in on_order_fill
    self.active_orders[nick] = CoinJoinOrder(self, nick, oid, amount, taker_pubkey)
  File "/usr/src/joinmarket/lib/maker.py", line 46, in __init__
    sys.exit(0)
SystemExit: 0

done

The `sys.exit` line is preceded by a debug print with 'wrongly using an already spent utxo' in the code (I've not actually seen that message, probably because debug output was not enabled when I ran the script?).

**Comment by chris-belcher** [comment]
You will need to post the entire log file so we can see the events leading up to the crash.

indent every line so it appears formatted

    code here
    code here
    code here

**Comment by domob1812** [comment]
I will see if this crash happens again (I'm again running a yield-generator with the exactly same configuration) and post the log file if the crash is reproduced.

**Comment by chris-belcher** [comment]
It should still be in the log file even if you restarted. Unless the file was deleted or something

**Comment by domob1812** [comment]
Unfortunately I don't have the logs anymore, and the crash did not occur again in the mean time.  From your description, this sounds indeed like a very possible explanation.  I'll close this issue here.  If I see the crash again, I'll post my logs to the other issue.
