### ISSUE TITLE
Threading problems

### ISSUE THREAD

**Issue by abitfan** [chris-belcher/joinmarket#82]
I haven't managed to hunt this down so I'm looking for input.
I was trying to debug #78 with ob-watcher.py and stumbled upon this:
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "ob-watcher.py", line 190, in run
    httpd = BaseHTTPServer.HTTPServer(hostport, OrderbookPageRequestHeader)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

This can be replicated by running ob-watcher.py and once connected cut off the connection
either by unplugging the network cable, networking restart or just use tcpkill: tcpkill -i eth0 port 6697

When networking is back ob-watcher.py reconnects to the irc network. When it does that successfully it tries to spawn the httpserver again even though thats already running.

**Comment by chris-belcher** [comment]
Oh yeah. That's because it starts the HTTP server in the on_welcome() callback

https://github.com/chris-belcher/joinmarket/blob/master/ob-watcher.py#L197
