### ISSUE TITLE
AttributeError: 'module' object has no attribute 'choice'

### ISSUE THREAD

**Issue by dreboli** [chris-belcher/joinmarket#92]
$python tumbler.py -x 0.003 -w 30 wallet.json address1 address2
...
tumble with these tx? (y/n):y
Enter wallet decryption passphrase:
[] downloading wallet history
...
connected to IRC
...
coinjoining 2423423424
...
[2015/05/26 15:45:51] randomly choosing orders with weighting
...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "tumbler.py", line 187, in run
    self.send_tx(tx, self.balance_by_mixdepth[tx['srcmixdepth']], sweep)
  File "tumbler.py", line 134, in send_tx
    orders, total_cj_fee = choose_order(self.taker.db, amount, tx['makercount'], weighted_order_choose)
  File "/home/user/joinmarkettor2/lib/common.py", line 365, in choose_order
    chosen_order = chooseOrdersBy(orders, n, lambda k: k[2])
  File "/home/user/joinmarkettor2/lib/common.py", line 323, in weighted_order_choose
    chosen_order_index = np.random.choice(len(orders), p=weight)
AttributeError: 'module' object has no attribute 'choice'

**Comment by chris-belcher** [comment]
You need numpy 1.7 or later.

**Comment by dreboli** [comment]
Yep, was my bad sorry about that.
